feat: add containerization
burntcarrot/blaezi pull request #2
Opened 2021-10-01 18:59 UTC by irvv17

Hi, hope this can help to resolve #1 

I've created a single Dockerfile that builds the Blaezi app and prepare it to use it with a docker run command like this (by downloading the image or by building it locally): 

```
docker run \ 
    --rm \
    -t \
    -v "$PWD/example.json":"/test.json" \
   -it 6f74bb4d078e https://google.com -tests "test.json"
```

- [x] Add Dockerfile
- [x] Build the image and save it to GPR
- [x] Test built image 
- [x] Add documentation of how to use it with

You can download the example of the built image and try it [my fork] (https://github.com/irvv17/blaezi/pkgs/container/blaezi%2Fblaezi-image)

2021-10-02 04:10 UTC, burntcarrot commented
Although someone else was assigned to this issue, your contribution is appreciated!

I have requested some changes as suggested above.

2021-10-02 04:19 UTC, burntcarrot commented
Uh oh, we have a failed build image workflow:

```
Error: Review the logs above, most likely you are using a package name associated with a different repository.  Rename your Image to fix. https://help.github.com/en/github/managing-packages-with-github-packages/about-github-packages#managing-packages for more information
````

2021-10-02 05:04 UTC, burntcarrot reviewed
Requesting changes here.

2021-10-02 07:16 UTC, burntcarrot requested changes
Looks good to me, just some more changes required before merging.

2021-10-02 07:16 UTC, burntcarrot commented on Dockerfile
> +RUN mkdir -p /go/src/github.com//burntcarrot/blaezi
Single slash after `github.com`.

2021-10-02 07:16 UTC, burntcarrot commented on .github/workflows/build-image.yml
> +          image-name: ${{env.DOCKER_IMAGE_NAME}}
The GPR [workflow](https://github.com/burntcarrot/blaezi/runs/3775081853?check_suite_focus=true) fails again. Is it due to the fact that the workflow is detecting your version of the image?

Here is the log:

```
Successfully tagged docker.pkg.github.com/burntcarrot/blaezi/blaezi:9676079db8a5a754e481dba96f5c373a10ca38e0
docker push docker.pkg.github.com/burntcarrot/blaezi/blaezi:9676079db8a5a754e481dba96f5c373a10ca38e0
The push refers to repository [docker.pkg.github.com/burntcarrot/blaezi/blaezi]
d63f1e779cab: Preparing
8021063fc4e1: Preparing
be2ac2444c94: Preparing
721384ec99e5: Preparing
denied: Resource not accessible by integration
Error: Review the logs above, most likely you are using a package name associated with a different repository.  Rename your Image to fix. https://help.github.com/en/github/managing-packages-with-github-packages/about-github-packages#managing-packages for more information
```

2021-10-02 07:16 UTC, burntcarrot commented on README.md
> +    - You can download the latest image on [gpr](https://github.com/burncarrot/blaezi/pkgs/container/blaezi%2Fblaezi-image) and just try it
`burntcarrot` as the username, please.

2021-10-02 16:03 UTC, irvv17 commented on Dockerfile
> +RUN mkdir -p /go/src/github.com//burntcarrot/blaezi
done.

2021-10-02 16:04 UTC, irvv17 commented on README.md
> +  ```
done.

2021-10-02 16:06 UTC, irvv17 commented
> Although someone else was assigned to this issue, your contribution is appreciated!
> 
> I have requested some changes as suggested below.

Sorry about that I've started working on the project and I didn't comment on the Issue, my mistake

2021-10-02 16:09 UTC, irvv17 commented on .github/workflows/build-image.yml
> +          image-name: ${{env.DOCKER_IMAGE_NAME}}
I've deleted my packages and changed the name of the image, hope it can store it with this.

2021-10-02 16:10 UTC, irvv17 commented on README.md
> +    - You can download the latest image on [gpr](https://github.com/burncarrot/blaezi/pkgs/container/blaezi%2Fblaezi-image) and just try it
done.

2021-10-02 16:20 UTC, burntcarrot commented on .github/workflows/build-image.yml
> +          image-name: ${{env.DOCKER_IMAGE_NAME}}
Your package seems to be still available on Github though. Anyways, I think the GPR workflow can be ignored for now, as it does not successfully pushing the image to the repo.

Could you please remove the action from the PR? And from the example too.

2021-10-02 16:22 UTC, burntcarrot commented on README.md
> +   ```
To be removed as suggested above. Could replace it with:

```
You can build the Docker image using:
```

2021-10-02 16:23 UTC, burntcarrot requested changes
Since the workflow fails, I think it is better to ignore it for now, running locally for now is totally okay. I think the addition of the workflow can be moved to a new issue.

2021-10-02 16:29 UTC, irvv17 commented
> Since the workflow fails, I think it is better to ignore it, for now, running locally, for now, is totally okay. I think the addition of the workflow can be moved to a new issue.

Okay let me remove it, I want to add a package just like vape, but I agree to move it on to another Issue.

2021-10-02 16:40 UTC, burntcarrot approved these changes
Looks good to me!

2021-10-02 16:41 UTC, irvv17 commented on README.md
> +   ```
the workflow is already removed also the instructions of how to use it in the README.md file

2021-10-02 16:43 UTC, burntcarrot commented
@irvv17 Thanks for your efforts, it's a great contribution! You've been highly co-operative throughout this PR!

Welcome to Hacktoberfest! Have fun! ☺

2021-10-02 16:44 UTC, merged

2021-10-02 16:57 UTC, irvv17 commented
> @irvv17 Thanks for your efforts, it's a great contribution! You've been highly co-operative throughout this PR!
> 
> Welcome to Hacktoberfest! Have fun! ☺

Thank you too and great project btw!
It would be nice to store the package if you need it.

2021-10-03 12:15 UTC, burntcarrot commented
Yes, I've been thinking of creating a new issue related to it, would you like to help with that?

Once you give a confirmation about your interest in working on it, I'll be happy to assign you to it.